[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  'forge-std=lib/forge-std/src',
  'openzeppelin=lib/openzeppelin-contracts/contracts',
  'solmate=lib/solmate/src',
]
deny_warnings = true

[profile.production]
optimizer = true
optimizer_runs = 10000000 # 10 million runs
via_ir = false
